#!/bin/bash

set -o errexit
set -o nounset

# Destination output directory
DIR=$3

# Set up logging
LOG=$DIR/log.txt
exec  > >(tee ${LOG})
exec 2>&1
set -o xtrace

TMP=$(mktemp -d)

# Destination contigs file
ASSEMBLY=$TMP/assembly/assembly.final.scaffolds.fasta

# Source reads in this container
INPUTS=$2

# Determine which process to run
PROC=$1
CMD=$(egrep ^${PROC}: /Procfile | cut -f 2 -d ':')

if [[ -z ${CMD} ]]; then
  echo "Abort, no proc found for ${PROC}."
  exit 1
fi

cd $TMP && eval ${CMD}
cp $ASSEMBLY $DIR/contigs.fa
