#!/bin/bash

set -o errexit
set -o nounset

# Destination output directory
DIR=$3

# Set up logging
LOG=$DIR/log.txt
exec  > >(tee ${LOG})
exec 2>&1
set -o xtrace

TMP=$(mktemp -d)

PREFIX='assembly'

# Source reads in this container
INPUTS=$2

# Determine which process to run
PROC=$1
CMD=$(egrep ^${PROC}: /Procfile | cut -f 2 -d ':')

if [[ -z ${CMD} ]]; then
  echo "Abort, no proc found for ${PROC}."
  exit 1
fi

cd $TMP && eval ${CMD}


# Destination scaffold or contigs file (only "contigs" produced for --metagenome)
ASSEMBLY=${TMP}/assembly.final.scaffolds.fasta
if [! -f $ASSEMBLY ]; then
  ASSEMBLY=${TMP}/assembly.contigs.fasta
fi
cp $ASSEMBLY $DIR/contigs.fa
